title: "データ構造とアルゴリズム"
summary: "アルゴリズムとそれを実現するためのデータ構造の学習はコンピュータサイエンスの根幹である。具体的なC言語などのサンプルプログラムの理解に終始するのではなく，疑似コードを使用するなどして応用的な事柄や，計算量の求め方などの理論的な内容について学習する。"
topics: ["データ構造", "アルゴリズム"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chapter1
  - chapter2
  - chapter3
  - chapter4
  - chapter5
  - chapter6
  - chapter7
